# Lesson 1

## Numpy
`numpy` is a library used for arrays numaric processing with ease, array is a data structure and it's fast in accessing data and processing because it's stored in an organized blocks in memory

<p dir='rtl'>
مكتبة <code>numpy</code> تستخدم للعمليات الحسابيه فى المصفوفات بسهوله, المصفوفه هى نوع بيانات للتخزين وهى سريعه فى الوصول الى البيانات ومعالجتها لأن البيانات تخزن فى الرامات مرتبه
</p>

In [53]:
import numpy as np

In [77]:
data = np.array([1,2,3])
print("add:", data + 2)
print("multiply:", data * 2)

add: [3 4 5]
multiply: [2 4 6]


## Data Types

### Integer Types: 
1. int8: 
    * (-128 to 127) 
    * size: 1 byte. 
2. int16: 
    * (-32,768 to 32,767)
    * size: 2 bytes. 
3. int32:
    * (-2,147,483,648 to 2,147,483,647)
    * size: 4 bytes. 
4. int64:
    * (-9,223,372,036,854,775,808 to 9,223,372,036,854,775,807)
    * size: 8 bytes.

### Unsigned Integer Types:
1. uint8: 
    * (0 to 255)
    * size: 1 byte.
2. uint16:
    * (0 to 65,535)
    * size: 2 bytes.
3. uint32:
    * (0 to 4,294,967,295)
    * size: 4 bytes.
4. uint64:
    * (0 to 18,446,744,073,709,551,615)
    * size: 8 bytes.

### Floating-Point Types: 
1. float16: 
    * Half-precision float
    * size: 2 bytes. 
2. float32: 
    * Single-precision float
    * size: 4 bytes. 
3. float64: 
    * Double-precision float
    * size: 8 bytes.


In [80]:
rn = np.arange(0, 7000, 2, dtype=np.uint16)
rn

array([   0,    2,    4, ..., 6994, 6996, 6998],
      shape=(3500,), dtype=uint16)

## 2D array
2d array is 2 dimintional array like rows and columns like Excel

<p dir='rtl'>المصفوفه 2d هى مصفوفه تعبر عن صفوف واعمده مثل Excel</p>

In [56]:
arr_2d = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
arr_2d.shape # 3x3

(3, 3)

In [58]:
arr_ran = np.arange(10).reshape([5,2])
arr_ran

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [59]:
ran_arr = np.random.randint(0, 700, [5,2]).astype(np.int16)
ran_arr

array([[617, 581],
       [115, 405],
       [145, 372],
       [695, 465],
       [436,  95]], dtype=int16)

In [60]:
candys = np.random.randint(10, 40, [3,3]).astype(np.int8)
candys

array([[20, 37, 14],
       [17, 10, 20],
       [30, 32, 26]], dtype=int8)

In [83]:
print(f"maximum number: {candys.max()}")
print(f"minimum number: {candys.min()}")
print(f"total sum: {candys.sum()}")
print(f"total mean: {candys.mean()}")

maximum number: 37
minimum number: 10
total sum: 206
total mean: 22.88888888888889


## Axis
* axis = 0 -> columns -> عواميد
* axis = 1 -> rows -> صفوف

In [62]:
print(f"maximum number per columns: {candys.max(axis=0)}")
print(f"maximum number per rows: {candys.max(axis=1)}")

maximum number per columns: [30 37 26]
maximum number per rows: [37 20 32]


In [63]:
print(f"minimum number per columns: {candys.min(axis=0)}")
print(f"minimum number per rows: {candys.min(axis=1)}")

minimum number per columns: [17 10 14]
minimum number per rows: [14 10 26]


In [64]:
print(f"total sum per columns: {candys.sum(axis=0)}")
print(f"total sum per rows: {candys.sum(axis=1)}")

total sum per columns: [67 79 60]
total sum per rows: [71 47 88]


In [65]:
print(f"mean per columns: {candys.mean(axis=0)}")
print(f"mean per rows: {candys.mean(axis=1)}")

mean per columns: [22.33333333 26.33333333 20.        ]
mean per rows: [23.66666667 15.66666667 29.33333333]
